name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install -e .[dev] hypothesis pytest-cov pytest-benchmark
      - name: Ruff (lint & format check)
        run: |
          ruff check .
          ruff format --check .
      - name: Mypy
        run: mypy src/sqlcanon
      - name: Tests (with coverage)
        run: pytest -q --cov=src/sqlcanon --cov-report=term-missing --cov-fail-under=85
